<?xml version="1.0" encoding="utf-8"?>
<TestRecord xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Tests>
    <TestRecord Name="MacdonaldSmith">
      <Tests>
        <TestRecord Name="Silk">
          <Tests>
            <TestRecord Name="Transport">
              <Tests>
                <TestRecord Name="Tests">
                  <Tests>
                    <TestRecord Name="TransportTests">
                      <Tests>
                        <TestRecord Name="TcpServerTest">
                          <Results>
                            <UnitTestResult>
                              <TestDate>2011-08-06T07:05:37</TestDate>
                              <Status>Failure</Status>
                              <TotalFailures>1</TotalFailures>
                              <TotalSuccess>0</TotalSuccess>
                              <TotalIgnored>0</TotalIgnored>
                              <Time />
                              <Message>System.Net.Sockets.SocketException : Address already in use
TearDown : System.Reflection.TargetInvocationException : Exception has been thrown by the target of an invocation.
  ----&gt; System.NullReferenceException : Object reference not set to an instance of an object</Message>
                              <StackTrace>  at System.Net.Sockets.Socket.Bind (System.Net.EndPoint local_end) [0x00000] in &lt;filename unknown&gt;:0 
  at System.Net.Sockets.TcpListener.Start (Int32 backlog) [0x00000] in &lt;filename unknown&gt;:0 
  at System.Net.Sockets.TcpListener.Start () [0x00000] in &lt;filename unknown&gt;:0 
  at MacdonaldSmith.Silk.Transport.TcpServer..ctor (Int32 port, ITcpServerListener tcpServerListener) [0x0004b] in /home/robert/Projects/Silk/MacdonaldSmith.Transport/TcpServer.cs:32 
  at MacdonaldSmith.Silk.Transport.Tests.TransportTests.SetUp () [0x00000] in /home/robert/Projects/Silk/MacdonaldSmith.Silk.Transport.Tests/TransportTests.cs:26 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 
--TearDown
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 
  at System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) [0x00000] in &lt;filename unknown&gt;:0 
  at NUnit.Core.TestMethod.doTearDown (NUnit.Core.TestCaseResult testResult) [0x00000] in &lt;filename unknown&gt;:0 
--NullReferenceException
  at MacdonaldSmith.Silk.Transport.Tests.TransportTests.TearDown () [0x00000] in /home/robert/Projects/Silk/MacdonaldSmith.Silk.Transport.Tests/TransportTests.cs:33 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
                              <ConsoleOutput />
                              <ConsoleError />
                            </UnitTestResult>
                            <UnitTestResult>
                              <TestDate>2011-08-06T07:10:50</TestDate>
                              <Status>Failure</Status>
                              <TotalFailures>1</TotalFailures>
                              <TotalSuccess>0</TotalSuccess>
                              <TotalIgnored>0</TotalIgnored>
                              <Time />
                              <Message>Did not receive a message from the client within 500ms.</Message>
                              <StackTrace>  at NUnit.Framework.Assert.Fail (System.String message, System.Object[] args) [0x00000] in &lt;filename unknown&gt;:0 
  at NUnit.Framework.Assert.Fail (System.String message) [0x00000] in &lt;filename unknown&gt;:0 
  at MacdonaldSmith.Silk.Transport.Tests.TransportTests.TcpServerTest () [0x0017a] in /home/robert/Projects/Silk/MacdonaldSmith.Silk.Transport.Tests/TransportTests.cs:104 
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (object,object[],System.Exception&amp;)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in &lt;filename unknown&gt;:0 </StackTrace>
                              <ConsoleOutput>Tcp Server mounted, listening on port 13000
Connecting client: 127.0.0.1:32856
Client connected
Reading message buffer...
Finished reading message buffer.
Message received on server: Hello World!
Connecting client: 127.0.0.1:39346
Client connected
Reading message buffer...
Finished reading message buffer.
Did not receive a message from the client within a reasonable time.
Message received on server: Hello Again.
</ConsoleOutput>
                              <ConsoleError />
                            </UnitTestResult>
                            <UnitTestResult>
                              <TestDate>2011-08-06T15:51:25</TestDate>
                              <Status>Success</Status>
                              <TotalFailures>0</TotalFailures>
                              <TotalSuccess>1</TotalSuccess>
                              <TotalIgnored>0</TotalIgnored>
                              <Time />
                              <Message>Test successful

Execution time: 0.07ms</Message>
                              <ConsoleOutput>Tcp Server mounted, listening on port 13000
Connecting client: 127.0.0.1:52737
Client connected
Reading message buffer...
Finished reading message buffer.
Message received on server: Hello World!
Pulsed, message recieved.
Connecting client: 127.0.0.1:35234
Client connected
Reading message buffer...
Finished reading message buffer.
Message received on server: Hello Again.
Pulsed, message recieved.
</ConsoleOutput>
                              <ConsoleError />
                            </UnitTestResult>
                          </Results>
                        </TestRecord>
                      </Tests>
                    </TestRecord>
                  </Tests>
                </TestRecord>
              </Tests>
            </TestRecord>
          </Tests>
        </TestRecord>
      </Tests>
    </TestRecord>
  </Tests>
</TestRecord>